[mypy]
python_version = 3.11
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
allow_untyped_defs = True
ignore_missing_imports = True
follow_imports = silent
exclude = (^tests/|^examples/)
disable_error_code = import-untyped,var-annotated,assignment,return-value
