#!/usr/bin/env python3
"""Convert the Jiang et al. (2020) Chinese financial sentiment dictionary
from upstream XLSX to the POS:/NEG: text format consumed by TextAnalyzer.

Source xlsx layout (one column per data sheet, header in row 1):
  - 'positive' sheet: 3338 words after header
  - 'negative' sheet: 5890 words after header
  - '说明' sheet:     citation metadata (skipped)

Run from repo root:
    python scripts/build_sentiment_dictionary.py

Re-run any time the source xlsx changes. The output overwrites the previous
runtime dictionary; cn_financial_sentiment.txt is checked in so this script
is mostly a refresh helper, not a build-time requirement.

See data/dictionaries/NOTICE.md for citation requirements before redistribution.
"""

from __future__ import annotations

import sys
from pathlib import Path

import openpyxl

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "data" / "dictionaries" / "source" / "中文金融情感词典_姜富伟等(2020).xlsx"
OUT = REPO_ROOT / "data" / "dictionaries" / "cn_financial_sentiment.txt"

POSITIVE_SHEET = "positive"
NEGATIVE_SHEET = "negative"

# Upstream README of the dictionary claims:
#   positive 3338, negative 5890, total 9228
# Those are RAW row counts in the xlsx. The xlsx contains intra-sheet duplicates
# (positive ~144, negative ~269), so after dedup the runtime dictionary is smaller.
# TextAnalyzer stores words in a set anyway, so deduping at build time is harmless
# and produces a smaller, cleaner file.
EXPECTED_POS_RAW = 3338
EXPECTED_NEG_RAW = 5890
RAW_DRIFT_TOLERANCE = 50  # alarm if upstream shifts beyond this


def extract_words(ws) -> list[str]:
    """Read column A, skip header row 0, strip whitespace, drop empties."""
    out: list[str] = []
    for i, row in enumerate(ws.iter_rows(values_only=True)):
        if i == 0:
            continue  # header row, e.g. ('Positive Word',)
        cell = row[0] if row else None
        if cell is None:
            continue
        word = str(cell).strip()
        if word:
            out.append(word)
    return out


def main() -> int:
    if not SRC.exists():
        print(f"ERROR source xlsx not found: {SRC}", file=sys.stderr)
        print(
            "Re-download from "
            "https://github.com/MengLingchao/Chinese_financial_sentiment_dictionary/",
            file=sys.stderr,
        )
        return 1

    wb = openpyxl.load_workbook(SRC, read_only=True, data_only=True)
    missing = [s for s in (POSITIVE_SHEET, NEGATIVE_SHEET) if s not in wb.sheetnames]
    if missing:
        print(
            f"ERROR source xlsx missing expected sheets {missing} (got {wb.sheetnames})",
            file=sys.stderr,
        )
        return 1

    pos_raw = extract_words(wb[POSITIVE_SHEET])
    neg_raw = extract_words(wb[NEGATIVE_SHEET])

    # Dedup within each list while preserving first-occurrence order
    pos_words = list(dict.fromkeys(pos_raw))
    neg_words = list(dict.fromkeys(neg_raw))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        f.write("# Chinese financial sentiment dictionary (POS:/NEG: format)\n")
        f.write("# Source: Jiang Fuwei et al. (2020), see data/dictionaries/NOTICE.md\n")
        f.write("# Generated by scripts/build_sentiment_dictionary.py — do not edit by hand\n")
        for w in pos_words:
            f.write(f"POS:{w}\n")
        for w in neg_words:
            f.write(f"NEG:{w}\n")

    print(
        f"positive: raw={len(pos_raw)} dedup={len(pos_words)} "
        f"(upstream dup {len(pos_raw) - len(pos_words)})"
    )
    print(
        f"negative: raw={len(neg_raw)} dedup={len(neg_words)} "
        f"(upstream dup {len(neg_raw) - len(neg_words)})"
    )
    print(f"total dedup: {len(pos_words) + len(neg_words)}")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")

    pos_drift = abs(len(pos_raw) - EXPECTED_POS_RAW)
    neg_drift = abs(len(neg_raw) - EXPECTED_NEG_RAW)
    if pos_drift > RAW_DRIFT_TOLERANCE or neg_drift > RAW_DRIFT_TOLERANCE:
        print(
            f"WARNING raw row counts drift more than {RAW_DRIFT_TOLERANCE} from "
            f"upstream README (positive {EXPECTED_POS_RAW}, negative {EXPECTED_NEG_RAW}). "
            "Verify upstream xlsx.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
